version: "2"
services:
  postgres-server:
    image: postgres:10.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=subr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.9
    ports:
      - "8080:8080"
    depends_on:
      - "postgres-server"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres-server:5432/subr
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET: adminaccess
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1pM3AktZjK5nEb54+K7Y\ny7J4JqYJBGUPRHO8FzLTGN7rPHEZ1+eJrG2J/YsHOJDdyyqo1BAAY0kO0+SsCEs0\nPKXCjCH0RXaTNDiZ88MgnwVfqSJzoiOC/3ts9G+xTNY2fK6HzKULzpBGtPauJi3P\nXswzcmvlgjeJ8jF/jfM1WFjGW7pNpIrxZhMvGoxAi0Cl3JvObO9EXCYwwUzCjrKY\ny/I5ZdrFV4d6Y9ZAfk8lhinSgx0VGq7i2z0dHSzaHAae4FvucvsjPBB+MeN6aydc\nfWa56SexZH2MDvoDZcBb2+4P47LC9YRvUR/CQXZcMonE2x1jgDx5etxb1Mgua3g5\nwQIDAQAB\n-----END PUBLIC KEY-----\n"}'
volumes:
  db_data:
